# Merge this value into c.Spawner.environment in jupyterhub_config.py.
# It supplies only the public origin. User paths remain generated by JupyterHub.
"MANSCI_PUBLIC_BASE_URL": "https://uclmansci2627.uksouth.cloudapp.azure.com",
